/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_sign_up.java
 *
 * Created on Jun 20, 2015, 11:24:01 PM
 */
package kemahasiswaan_10113112_10113135;
import java.awt.Color;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author BankZeck182
 */
public class frm_sign_up extends javax.swing.JFrame {
koneksi dbsetting;
String driver,database,user,pass;
Object tabel;

    /** Creates new form frm_sign_up */
    public frm_sign_up() {
        initComponents();
        
        dbsetting = new koneksi();
        driver    = dbsetting.SettingPanel("DBDriver");
        database  = dbsetting.SettingPanel("DBDatabase");
        user      = dbsetting.SettingPanel("DBUsername");
        pass      = dbsetting.SettingPanel("DBPassword");
        
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_pengguna = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        txt_vpass = new javax.swing.JPasswordField();
        txt_test = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_test1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_pertanyaan = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txt_lainnya = new javax.swing.JTextField();
        txt_jawaban = new javax.swing.JTextField();
        btn_kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setText("Nama Lengkap             :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setText("Nama Pengguna           :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("Password                     :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel5.setForeground(new java.awt.Color(102, 204, 255));
        jLabel5.setText("Verifikasi Password     :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        txt_nama.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_nama.setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 184, -1));

        txt_pengguna.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_pengguna.setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().add(txt_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 130, -1));

        txt_pass.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_pass.setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 130, -1));

        txt_vpass.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_vpass.setForeground(new java.awt.Color(102, 204, 255));
        txt_vpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_vpassKeyReleased(evt);
            }
        });
        getContentPane().add(txt_vpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 130, -1));

        txt_test.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_test.setForeground(new java.awt.Color(255, 0, 0));
        txt_test.setText("jLabel6");
        getContentPane().add(txt_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jButton1.setFont(new java.awt.Font("Vijaya", 0, 18));
        jButton1.setText("Daftar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        txt_test1.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_test1.setForeground(new java.awt.Color(255, 0, 0));
        txt_test1.setText("jLabel6");
        getContentPane().add(txt_test1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setText("Pertanyaan Keamanan :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        combo_pertanyaan.setFont(new java.awt.Font("Vijaya", 0, 18));
        combo_pertanyaan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "~Silahkan Pilih~", "Dimanakah tempat lahir kamu?", "Apa warna favorit  kamu?", "Dari mana asal sekolah kamu?", "Apa makanan kesukaan kamu?", "Lainnya" }));
        combo_pertanyaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_pertanyaanActionPerformed(evt);
            }
        });
        getContentPane().add(combo_pertanyaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 180, -1));

        jLabel7.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel7.setForeground(new java.awt.Color(102, 204, 255));
        jLabel7.setText("Jawaban :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        txt_lainnya.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_lainnya.setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().add(txt_lainnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 99, -1));

        txt_jawaban.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_jawaban.setForeground(new java.awt.Color(102, 204, 255));
        getContentPane().add(txt_jawaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 99, -1));

        btn_kembali.setFont(new java.awt.Font("Vijaya", 0, 18));
        btn_kembali.setText("Kembali");
        btn_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("FORM SIGN UP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 110, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10113112_10113135/bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 470));

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    String data[] = new String[4];
    Date tanggal = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tgl = sdf.format(tanggal);
    
    if ((txt_nama.getText().isEmpty()) || 
            (txt_pengguna.getText().isEmpty()) || 
            (txt_pass.getText().isEmpty()) ||
            (txt_vpass.getText().isEmpty()) ||
            (txt_jawaban.getText().isEmpty()) ||
            (combo_pertanyaan.getSelectedItem()=="~Silahkan Pilih~"))
    {
        JOptionPane.showMessageDialog(null, 
                "Data tidak boleh ada yang kosong, Silahkan dilengkapi");
        txt_nama.requestFocus();
    }
    
    else
    {
        if (txt_pass.getText().equals(txt_vpass.getText()))
        {
            if(combo_pertanyaan.getSelectedItem()!="Lainnya")
            {
                try
                {
                    Class.forName(driver);
                    Connection kon = DriverManager.getConnection(
                         database,
                         user,
                         pass);
                    Statement stt = kon.createStatement();
                    String SQL    = "INSERT INTO `t_pengguna`(`nama_lengkap`,"
                         + "`pengguna`,"
                         + "`password`,"
                            + "`tgl`,"
                            + "`jml_error`,"
                            + "`pertanyaan_keamanan`,"
                            + "`jawaban`)"
                            + "Value"
                      + "( '"+txt_nama.getText()+"',"
                      + " '"+txt_pengguna.getText()+"' ,"
                      + " '"+txt_pass.getText()+"' ,"
                      + " '"+tgl+"' ,"
                      + " '0' ,"
                      + " '"+combo_pertanyaan.getSelectedItem()+"' ,"
                      + " '"+txt_jawaban.getText()+"')";

                    stt.executeUpdate(SQL);
                    JOptionPane.showMessageDialog(null, "Anda Berhasil Daftar, Silahkan Login");
                    stt.close();
                    kon.close();
                    frm_login a = new frm_login();
                    a.setVisible(true);
                    this.setVisible(false);
                }

                catch (Exception ex)
                {
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null,
                        "Nama Pengguna Sudah Ada","Pesan",
                        JOptionPane.INFORMATION_MESSAGE);
                    txt_test.setText("Sudah Ada");
                }
            }
            else if(combo_pertanyaan.getSelectedItem()=="Lainnya")
            {
                if((txt_lainnya.getText()!=null) || (txt_lainnya.getText()!=""))
                {
                    try
                    {
                        Class.forName(driver);
                        Connection kon = DriverManager.getConnection(
                             database,
                             user,
                             pass);
                        Statement stt = kon.createStatement();
                        String SQL    = "INSERT INTO `t_pengguna`(`nama_lengkap`,"
                             + "`pengguna`,"
                             + "`password`,"
                                + "`tgl`,"
                                + "`jml_error`,"
                                + "`pertanyaan_keamanan`,"
                                + "`jawaban`)"
                                + "Value"
                          + "( '"+txt_nama.getText()+"',"
                          + " '"+txt_pengguna.getText()+"' ,"
                          + " '"+txt_pass.getText()+"' ,"
                          + " '"+tgl+"' ,"
                          + " '0' ,"
                          + " '"+txt_lainnya.getText()+"' ,"
                          + " '"+txt_jawaban.getText()+"')";

                        stt.executeUpdate(SQL);
                        JOptionPane.showMessageDialog(null, "Anda Berhasil Daftar, Silahkan Login");
                        stt.close();
                        kon.close();
                        frm_login a = new frm_login();
                        a.setVisible(true);
                        this.setVisible(false);
                    }
                    catch (Exception ex)
                    {
                        System.err.println(ex.getMessage());
                        JOptionPane.showMessageDialog(null,
                            "Nama Pengguna Sudah Ada","Pesan",
                            JOptionPane.INFORMATION_MESSAGE);
                        txt_test.setText("Sudah Ada");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, 
                    "data tidak boleh ada yang kosong, silahkan dilengkapi");
                    txt_lainnya.requestFocus();
                }
            }
        }
        else
        {
            txt_test1.setText("Password Tidak Sama");
        }
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    txt_test.setText("");
    txt_test1.setText("");
    txt_lainnya.setEnabled(false);
}//GEN-LAST:event_formWindowOpened

    private void combo_pertanyaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_pertanyaanActionPerformed
        // TODO add your handling code here:
        if(combo_pertanyaan.getSelectedItem()=="Lainnya")
        {
            txt_lainnya.setEnabled(true);
            txt_lainnya.requestFocus();
        }
        else
        {
            txt_lainnya.setEnabled(false);
            combo_pertanyaan.requestFocus();
        }
    }//GEN-LAST:event_combo_pertanyaanActionPerformed

private void btn_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembaliActionPerformed
// TODO add your handling code here:
    frm_login a = new frm_login();
    a.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_btn_kembaliActionPerformed

private void txt_vpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_vpassKeyReleased
// TODO add your handling code here:
    if(txt_pass.getText().equals(txt_vpass.getText()))
        {
            
            txt_test1.setText(("Password Cocok"));
            txt_test1.setForeground(Color.GREEN);
        }
        else
        {
            txt_test1.setText(("Password Tidak Cocok"));
            txt_test1.setForeground(Color.RED);
        }
}//GEN-LAST:event_txt_vpassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frm_sign_up().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembali;
    private javax.swing.JComboBox combo_pertanyaan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_jawaban;
    private javax.swing.JTextField txt_lainnya;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_pengguna;
    private javax.swing.JLabel txt_test;
    private javax.swing.JLabel txt_test1;
    private javax.swing.JPasswordField txt_vpass;
    // End of variables declaration//GEN-END:variables
}
