/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_lupa_password.java
 *
 * Created on Jun 30, 2015, 5:45:37 PM
 */
package kemahasiswaan_10113112_10113135;
import java.awt.Color;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Eggys
 */
public class frm_lupa_password extends javax.swing.JFrame {
koneksi dbsetting;
String driver,database,user,pass;
Object tabel;
    /** Creates new form frm_lupa_password */
    public frm_lupa_password() {
        initComponents();
        dbsetting = new koneksi();
        driver    = dbsetting.SettingPanel("DBDriver");
        database  = dbsetting.SettingPanel("DBDatabase");
        user      = dbsetting.SettingPanel("DBUsername");
        pass      = dbsetting.SettingPanel("DBPassword");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_pengguna = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        pertanyaan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_jawaban = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_psw_baru = new javax.swing.JTextField();
        txt_vpsw_baru = new javax.swing.JTextField();
        btn_ubah = new javax.swing.JButton();
        txt_test1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tanya = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vijaya", 0, 18));
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Masukkan Pengguna       :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        txt_pengguna.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_pengguna.setForeground(new java.awt.Color(51, 153, 255));
        getContentPane().add(txt_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 139, -1));

        btn_cari.setFont(new java.awt.Font("Vijaya", 0, 18));
        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        pertanyaan.setFont(new java.awt.Font("Vijaya", 0, 18));
        pertanyaan.setForeground(new java.awt.Color(51, 204, 255));
        pertanyaan.setText("Pertanyaan");
        getContentPane().add(pertanyaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Vijaya", 0, 18));
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("Jawaban                         :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        txt_jawaban.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_jawaban.setForeground(new java.awt.Color(51, 153, 255));
        getContentPane().add(txt_jawaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 141, -1));

        btn_submit.setFont(new java.awt.Font("Vijaya", 0, 18));
        btn_submit.setText("Ceck Jawaban");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 141, -1));

        jLabel4.setFont(new java.awt.Font("Vijaya", 0, 18));
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Password Baru                :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Vijaya", 0, 18));
        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setText("Verifikasi Password Baru :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        txt_psw_baru.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_psw_baru.setForeground(new java.awt.Color(51, 153, 255));
        getContentPane().add(txt_psw_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 142, -1));

        txt_vpsw_baru.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_vpsw_baru.setForeground(new java.awt.Color(51, 153, 255));
        txt_vpsw_baru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_vpsw_baruKeyReleased(evt);
            }
        });
        getContentPane().add(txt_vpsw_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 142, -1));

        btn_ubah.setFont(new java.awt.Font("Vijaya", 0, 18));
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        txt_test1.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_test1.setForeground(new java.awt.Color(255, 0, 0));
        txt_test1.setText("jLabel2");
        getContentPane().add(txt_test1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Vijaya", 0, 18));
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        tanya.setFont(new java.awt.Font("Vijaya", 0, 18));
        tanya.setForeground(new java.awt.Color(51, 204, 255));
        tanya.setText("Pertanyaan                     :");
        getContentPane().add(tanya, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("FORM LUPA PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10113112_10113135/bg2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        if(txt_pengguna.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, 
                "Data tidak boleh ada yang kosong, Silahkan dilengkapi");
        }
        else
        {
            //cek pengguna ada atau tidak
            try
            {
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(
                     database,
                     user,
                     pass);
                Statement stt = kon.createStatement();
                String SQL    = "select * from t_pengguna where BINARY pengguna='"+txt_pengguna.getText()+"'";
                ResultSet res = stt.executeQuery(SQL);
                //jika pengguna ada maka
                if(res.next())
                {
                    tanya.setText("Pertanyaan");
                    pertanyaan.setText(res.getString(6));
                    txt_jawaban.setEnabled(true);
                    btn_submit.setEnabled(true);
                    txt_jawaban.requestFocus();
                    txt_pengguna.setEnabled(false);
                    btn_cari.setEnabled(false);
                }
                //jika tidak
                else
                {
                    JOptionPane.showMessageDialog(null, "Nama Pengguna Tidak Ditemukan atau Tidak Terdaftar",
                            "Pesan",JOptionPane.ERROR_MESSAGE);
                }
                res.close();
                stt.close();
                kon.close();
            }

            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txt_jawaban.setEnabled(false);
        txt_psw_baru.setEnabled(false);
        txt_vpsw_baru.setEnabled(false);
        btn_submit.setEnabled(false);
        btn_ubah.setEnabled(false);
        txt_test1.setText("");
        tanya.setText("");
        pertanyaan.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        if(txt_jawaban.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, 
                "Data tidak boleh ada yang kosong, Silahkan dilengkapi");
        }
        else
        {
            //cek jawaban pertanyaan keamanan sama atau tidak
            try
            {
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(
                     database,
                     user,
                     pass);
                Statement stt = kon.createStatement();
                String SQL    = "select * from t_pengguna where BINARY pengguna='"+txt_pengguna.getText()+"' AND pertanyaan_keamanan='"+pertanyaan.getText()+"'";
                ResultSet res = stt.executeQuery(SQL);
                //jika pengguna dan pertanyaan keamanan sesuai maka...
                if(res.next())
                {
                    //jika jawaban benar maka...
                    if(res.getString(7).equals(txt_jawaban.getText()))
                    {
                        txt_psw_baru.setEnabled(true);
                        txt_vpsw_baru.setEnabled(true);
                        txt_psw_baru.requestFocus();
                        txt_jawaban.setEnabled(false);
                        btn_submit.setEnabled(false);
                        btn_ubah.setEnabled(true);
                    }
                    //jika jawaban salah maka...
                    else
                    {
                        JOptionPane.showMessageDialog(null,
                        "Jawaban Anda salah","Pesan",
                        JOptionPane.ERROR_MESSAGE);
                        txt_jawaban.requestFocus();
                    }
                }
                //jika tidak
                else
                {
                    JOptionPane.showMessageDialog(null, "Nama Pengguna / Pertanyaan Tidak Ditemukan atau Tidak Terdaftar",
                            "Pesan",JOptionPane.ERROR_MESSAGE);
                }
                res.close();
                stt.close();
                kon.close();
            }

            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        //jika password dan verifikasi password sama
        if (txt_psw_baru.getText().equals(txt_vpsw_baru.getText()))
        {
            //update password
            try
            {
                Class.forName(driver);
                Connection kon = DriverManager.getConnection(
                     database,
                     user,
                     pass);
                Statement stt = kon.createStatement();
                String SQL    = "UPDATE `t_pengguna` set `password` = '"+txt_psw_baru.getText()+"' where pengguna='"+txt_pengguna.getText()+"'";
                stt.executeUpdate(SQL);
                JOptionPane.showMessageDialog(null, "Password berhasil di ubah","Pesan",JOptionPane.INFORMATION_MESSAGE);
                stt.close();
                kon.close();
            }

            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            txt_test1.setText("Password Tidak Sama");
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frm_login a = new frm_login();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

private void txt_vpsw_baruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_vpsw_baruKeyReleased
// TODO add your handling code here:
    if(txt_psw_baru.getText().equals(txt_vpsw_baru.getText()))
        {
            
            txt_test1.setText(("Password Cocok"));
            txt_test1.setForeground(Color.GREEN);
        }
        else
        {
            txt_test1.setText(("Password Tidak Cocok"));
            txt_test1.setForeground(Color.RED);
        }
}//GEN-LAST:event_txt_vpsw_baruKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_lupa_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frm_lupa_password().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel pertanyaan;
    private javax.swing.JLabel tanya;
    private javax.swing.JTextField txt_jawaban;
    private javax.swing.JTextField txt_pengguna;
    private javax.swing.JTextField txt_psw_baru;
    private javax.swing.JLabel txt_test1;
    private javax.swing.JTextField txt_vpsw_baru;
    // End of variables declaration//GEN-END:variables
}
