/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_login.java
 *
 * Created on Jun 20, 2015, 10:53:40 PM
 */
package kemahasiswaan_10113112_10113135;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author BankZeck182
 */
public class frm_login extends javax.swing.JFrame {

koneksi dbsetting;
String driver,database,user,pass;
Object tabel;
    /** Creates new form frm_login */
    public frm_login() {
        initComponents();
        
        dbsetting = new koneksi();
        driver    = dbsetting.SettingPanel("DBDriver");
        database  = dbsetting.SettingPanel("DBDatabase");
        user      = dbsetting.SettingPanel("DBUsername");
        pass      = dbsetting.SettingPanel("DBPassword");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_sign_up = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_pengguna = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_lupa_password = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10113112_10113135/bg1.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Klik");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txt_sign_up.setFont(new java.awt.Font("Vijaya", 1, 18));
        txt_sign_up.setForeground(new java.awt.Color(255, 0, 255));
        txt_sign_up.setText("Sign Up");
        txt_sign_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_sign_upMouseClicked(evt);
            }
        });
        getContentPane().add(txt_sign_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel6.setForeground(new java.awt.Color(102, 153, 255));
        jLabel6.setText("Untuk Melakukan Pendaftaran");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel2.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("Nama Pengguna");

        txt_pengguna.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_pengguna.setForeground(new java.awt.Color(51, 153, 255));

        txt_password.setFont(new java.awt.Font("Vijaya", 0, 18));
        txt_password.setForeground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("Password");

        btn_login.setFont(new java.awt.Font("Vijaya", 0, 18));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Vijaya", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btn_login)
                .addContainerGap(58, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txt_pengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(txt_password))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_login)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 180, -1));

        txt_lupa_password.setFont(new java.awt.Font("Vijaya", 1, 18));
        txt_lupa_password.setForeground(new java.awt.Color(255, 0, 255));
        txt_lupa_password.setText("Lupa Kata Sandi Anda?");
        txt_lupa_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_lupa_passwordMouseClicked(evt);
            }
        });
        getContentPane().add(txt_lupa_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kemahasiswaan_10113112_10113135/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 460));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-363)/2, (screenSize.height-499)/2, 363, 499);
    }// </editor-fold>//GEN-END:initComponents

private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String tgl_sekarang = null;
// TODO add your handling code here:
    try
    {
        Class.forName(driver);
        Connection kon = DriverManager.getConnection(
                database,
                user,
                pass);
        Statement stt  = kon.createStatement();
        String SQL     = "SELECT * FROM `t_pengguna` WHERE BINARY `pengguna` ='"
                +txt_pengguna.getText()+"'";
        ResultSet res = stt.executeQuery(SQL);
        
        //jika username ada
        if(res.next())
        {
            try
            {
                Class.forName(driver);
                Connection kon2 = DriverManager.getConnection(
                        database,
                        user,
                        pass);
                Statement stt2  = kon2.createStatement();
                String SQL2     = "SELECT * FROM `t_pengguna` WHERE BINARY `pengguna` ='"
                        +txt_pengguna.getText()+"' and BINARY `password` ='"+txt_password.getText()+"'";
                ResultSet res2 = stt2.executeQuery(SQL2);
                
                //jika username dan password ada
                if(res2.next())
                {
                    //mengambil tanggal sekarang
                    Date tanggal_sekarang = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    tgl_sekarang = sdf.format(tanggal_sekarang);
                    //cek tanggal sekarang dengan tanggal yang di database untuk username yang bersangkutan
                    try
                    {
                        Class.forName(driver);
                        Connection kon2_2 = DriverManager.getConnection(
                                database,
                                user,
                                pass);
                        Statement stt2_2  = kon2_2.createStatement();
                        String SQL2_2     = "SELECT * FROM `t_pengguna` WHERE BINARY `pengguna` ='"
                                +txt_pengguna.getText()+"'";
                        ResultSet res2_2 = stt2_2.executeQuery(SQL2_2);

                        //jika username ada
                        if(res2_2.next())
                        {
                            //jika tanggal sekarang sama dengan tanggal yang di database
                            //convert date dari database ke string
                            Date db1 = new Date();
                            db1 = res2_2.getDate(4);
                            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
                            String db_tgl = sdf2.format(db1);

                              if(tgl_sekarang.equals(db_tgl))
                              {

                                  //jumlah error sama dengan sebelumnya dari database
                                  try
                                    {
                                        Class.forName(driver);
                                        Connection kon2_3 = DriverManager.getConnection(
                                                database,
                                                user,
                                                pass);
                                        Statement stt2_3  = kon2_3.createStatement();
                                        String SQL2_3     = "UPDATE t_pengguna set jml_error='"+res2_2.getInt(5)+"' WHERE `pengguna` ='"
                                                +txt_pengguna.getText()+"'";
                                        stt2_3.executeUpdate(SQL2_3);
                                        kon2_3.close();
                                        stt2_3.close();
                                    }
                                    catch(Exception ex)
                                    {
                                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                                        System.err.println("Kesalahan saat update jumlah error sama dengan database");
                                    }
                              }
                              //jika tanggal sekarang tidak sama dengan tanggal di dtaabase
                              else
                              {
                                  //ubah jumlah error menjadi 0
                                   try
                                    {
                                        Class.forName(driver);
                                        Connection kon2_4 = DriverManager.getConnection(
                                                database,
                                                user,
                                                pass);
                                        Statement stt2_4  = kon2_4.createStatement();
                                        String SQL2_4     = "UPDATE t_pengguna set tgl='"+tgl_sekarang+"', jml_error='0' WHERE `pengguna` ='"
                                                +txt_pengguna.getText()+"'";
                                        stt2_4.executeUpdate(SQL2_4);
                                        kon2_4.close();
                                        stt2_4.close();
                                    }
                                    catch(Exception ex)
                                    {
                                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                                        System.err.println("Kesalahan saat update tanggal sekarang dan jumlah error menjadi 0");
                                    }
                              }
                        }    
                        kon2_2.close();
                        res2_2.close();
                        stt2_2.close();
                    }
                    catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                        System.err.println("Kesalahan ketika cek tanggal sekarang dengan database");
                    }
                    
                    
                    //mengecek apakah jumlah error sudah lebih atau sama dengan 3, jika ya maka di blokir jika tidak maka bisa masuk menu
                    try
                    {
                        Class.forName(driver);
                        Connection kon2_5 = DriverManager.getConnection(
                                database,
                                user,
                                pass);
                        Statement stt2_5  = kon2_5.createStatement();
                        String SQL2_5     = "SELECT * FROM `t_pengguna` WHERE BINARY `pengguna` ='"
                                            +txt_pengguna.getText()+"' and BINARY `password` ='"+txt_password.getText()+"'";
                        ResultSet res2_5 =stt2_5.executeQuery(SQL2_5);
                        if(res2_5.next())
                        {
                            if(res2_5.getInt(5)<3)
                            {
                                JOptionPane.showMessageDialog(null, "Anda Berhasil Masuk","Pesan",JOptionPane.INFORMATION_MESSAGE);
                                new frm_utama().show();
                                dispose();
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Anda Sudah DIblokir","Pesan",JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                        kon2_5.close();
                        stt2_5.close();
                    }
                    catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                        System.err.println("Kesalahan saat select/cek jumlah error"); 
                    }
//                        
                }  
                //jika username ada tapi password salah
                else
                {
                     int jml_error = 0;
                    //mengambil tanggal sekarang
                    Date tanggal_sekarang = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    tgl_sekarang = sdf.format(tanggal_sekarang);

                    //cek tanggal sekarang dengan tanggal yang di database untuk username yang bersangkutan
                    try
                    {
                        Class.forName(driver);
                        Connection kon3 = DriverManager.getConnection(
                                database,
                                user,
                                pass);
                        Statement stt3  = kon3.createStatement();
                        String SQL3     = "SELECT * FROM `t_pengguna` WHERE BINARY `pengguna` ='"
                                +txt_pengguna.getText()+"'";
                        ResultSet res3 = stt3.executeQuery(SQL3);

                        //jika username ada
                        if(res3.next())
                        {
                            
                            //convert date dari database ke string
                            Date db1 = new Date();
                            db1 = res3.getDate(4);
                            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
                            String db_tgl = sdf.format(db1);

                              if(tgl_sekarang.equals(db_tgl)) //jika tanggal sekarang sama dengan tanggal yang di database
                              {
                                  //jumlah error sama dengan sebelumnya dari database
                                  try
                                    {
                                        Class.forName(driver);
                                        Connection kon4 = DriverManager.getConnection(
                                                database,
                                                user,
                                                pass);
                                        Statement stt4  = kon4.createStatement();
                                        String SQL4     = "UPDATE t_pengguna set jml_error='"+res3.getInt(5)+"' WHERE `pengguna` ='"
                                                +txt_pengguna.getText()+"'";
                                        stt4.executeUpdate(SQL4);

                                        jml_error=res3.getInt(5);
                                        kon4.close();
                                        stt4.close();
                                    }
                                    catch(Exception ex)
                                    {
                                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                                        System.err.println("Kesalahan saat update jumlah error sama dengan database");
                                    }
                              }
                              //jika tanggal sekarang tidak sama dengan tanggal di dtaabase
                              else
                              {
                                  //ubah jumlah error menjadi 0
                                   try
                                    {
                                        Class.forName(driver);
                                        Connection kon5 = DriverManager.getConnection(
                                                database,
                                                user,
                                                pass);
                                        Statement stt5  = kon5.createStatement();
                                        String SQL5     = "UPDATE t_pengguna set tgl='"+tgl_sekarang+"', jml_error='0' WHERE `pengguna` ='"
                                                +txt_pengguna.getText()+"'";
                                        System.out.println(SQL5);
                                        stt5.executeUpdate(SQL5);
                                        jml_error=0;
                                        kon5.close();
                                        stt5.close();
                                    }
                                    catch(Exception ex)
                                    {
                                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                                        System.err.println("Kesalahan saat update tanggal sekarang dan jumlah error menjadi 0");
                                    }
                              }
                        }    
                        kon3.close();
                        res3.close();
                        stt3.close();
                    }
                    catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                        System.err.println("Kesalahan ketika cek tanggal sekarang dengan database");
                    }
                    
                    //cek apakah jumlah errornya melebebihi 3? *
                    try
                    {
                        Class.forName(driver);
                        Connection kon22 = DriverManager.getConnection(
                                database,
                                user,
                                pass);   
                        Statement stt22  = kon22.createStatement();
                        String SQL22     = "SELECT * FROM `t_pengguna` WHERE BINARY `pengguna` ='"
                                +txt_pengguna.getText()+"'";
                        ResultSet res22 = stt22.executeQuery(SQL22);
                        if(res22.next())
                        {
                            //* jika ya
                            //JOptionPane.showMessageDialog(null, res2_2.getInt(5));
                            if(res22.getInt(5)>2)
                            {
                                JOptionPane.showMessageDialog(null, "Anda Sudah Diblokir","Pesan",JOptionPane.INFORMATION_MESSAGE);
                            }
                            //* jika tidak
                            else
                            {
                                //menambah 1 pada jumlah error dengan username yang bersangkutan
                                JOptionPane.showMessageDialog(null, "Password Salah",
                                        "Pesan",JOptionPane.ERROR_MESSAGE);

                                try
                                {
                                    jml_error = jml_error + 1;
                                    Class.forName(driver);
                                    Connection kon6 = DriverManager.getConnection(
                                            database,
                                            user,
                                            pass);
                                    Statement stt6  = kon6.createStatement();
                                    String SQL6     = "UPDATE t_pengguna set jml_error='"+jml_error+"' WHERE `pengguna` ='"
                                            +txt_pengguna.getText()+"'";
                                    stt6.executeUpdate(SQL6);
                                        try
                                        {
                                            Class.forName(driver);
                                            Connection kon6_2 = DriverManager.getConnection(
                                                    database,
                                                    user,
                                                    pass);   
                                            Statement stt6_2  = kon6_2.createStatement();
                                            String SQL6_2     = "SELECT * FROM `t_pengguna` WHERE BINARY `pengguna` ='"
                                                    +txt_pengguna.getText()+"'";
                                            ResultSet res6_2 = stt6_2.executeQuery(SQL6_2);
                                            if(res6_2.next())
                                            {
                                                //* jika ya
                                                //JOptionPane.showMessageDialog(null, res2_2.getInt(5));
                                                if(res6_2.getInt(5)>2)
                                                {
                                                    System.exit(0);
                                                }
                                            }
                                            res6_2.close();
                                            stt6_2.close();
                                            kon6_2.close();
                                        }
                                        catch(Exception ex)
                                        {
                                            JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                                        }
                                    kon6.close();
                                    stt6.close();
                                }
                                catch(Exception ex)
                                {
                                    JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                                    System.err.println("Kesalahan saat update jumlah error menjadi di tambah 1");
                                }
                            }
                            
                            kon22.close();
                            stt22.close();
                        }
                    }
                    catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                kon2.close();
                res2.close();
                stt2.close();
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
            }    
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nama Pengguna Tidak Ditemukan atau Tidak Terdaftar",
                        "Pesan",JOptionPane.ERROR_MESSAGE);
        }    
        res.close();
        stt.close();
        kon.close();    
        
    }
    catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);       
    }
}//GEN-LAST:event_btn_loginActionPerformed

private void txt_sign_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_sign_upMouseClicked
// TODO add your handling code here:
    frm_sign_up a = new frm_sign_up();
    a.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_txt_sign_upMouseClicked

private void txt_lupa_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lupa_passwordMouseClicked
// TODO add your handling code here:
    frm_lupa_password a = new frm_lupa_password();
    a.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_txt_lupa_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frm_login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_lupa_password;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_pengguna;
    private javax.swing.JLabel txt_sign_up;
    // End of variables declaration//GEN-END:variables
}
